name: Generate JSon Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Jsonresume convert
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: andrelanrezac/latex:latest:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            python3 prepare_resume.py assets/json/template_resume.json assets/tex/template_resume.tex 
            pdflatex assets/tex/output.tex
