name: Generate JSon Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Jsonresume convert
        uses: addnab/docker-run-action@v3
        with:
          image: andrelanrezac/latex:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            python3 prepare_resume.py assets/json/template_resume.json assets/tex/template_resume.tex 
            pdflatex assets/tex/output.tex
