name: Generate JSon Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: andrelanrezac/latex:latest

      - name: Run Jsonresume convert
        uses: addnab/docker-run-action@v3
        with:
          image: andrelanrezac/latex:v0.03
          options: -v ${{ github.workspace }}:/data
          run: |
            python3 /usr/local/bin/prepare_resume.py assets/json/resume_en-us.json assets/tex/template_resume.tex -o assets/tex/resume_en-us.tex
            lualatex -output-directory=assets/pdf/en-us assets/tex/resume_en-us.tex
            biber assets/pdf/en-us/resume_en-us.bcf
            lualatex -output-directory=assets/pdf/en-us assets/tex/resume_en-us.tex
            

