name: Generate JSon Resume

on:
  push:
    branches:
      - main
    paths:
      - 'assets/json/**'
      - 'assets/tex/**'
  workflow_dispatch:

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Jsonresume convert
        uses: addnab/docker-run-action@v3
        with:
          image: andrelanrezac/latex:v0.04
          options: -v ${{ github.workspace }}:/data
          run: |
            python3 /usr/local/bin/prepare_resume.py assets/json/resume_en-us.json assets/tex/template_resume.tex -o assets/tex/resume_en-us.tex
            lualatex -output-directory=assets/pdf/en-us assets/tex/resume_en-us.tex
            biber assets/pdf/en-us/resume_en-us.bcf
            lualatex -output-directory=assets/pdf/en-us assets/tex/resume_en-us.tex
            python3 /usr/local/bin/prepare_resume.py assets/json/resume_fr-fr.json assets/tex/template_resume.tex -o assets/tex/resume_fr-fr.tex
            lualatex -output-directory=assets/pdf/fr-fr assets/tex/resume_fr-fr.tex
            biber assets/pdf/fr-fr/resume_fr-fr.bcf
            lualatex -output-directory=assets/pdf/fr-fr assets/tex/resume_fr-fr.tex

      - name: Commit and push generated PDFs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/pdf
          git commit -m "Update generated PDFs"
          git push origin main


